# Generated by Django 3.2.8 on 2021-10-11 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('sort_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('seo_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(blank=True, max_length=5000)),
                ('mpaa_rating', models.CharField(blank=True, max_length=100)),
                ('critics_pick', models.IntegerField(blank=True)),
                ('byline', models.CharField(blank=True, max_length=500)),
                ('headline', models.CharField(blank=True, max_length=400)),
                ('summary_short', models.CharField(blank=True, max_length=500)),
                ('publication_date', models.CharField(blank=True, max_length=100)),
                ('opening_date', models.CharField(max_length=100)),
                ('date_updated', models.CharField(blank=True, max_length=100)),
                ('bookmark', models.ManyToManyField(blank=True, related_name='bookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reviews.review')),
                ('type', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('suggested_link_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reviews.review')),
                ('type', models.CharField(max_length=100)),
                ('src', models.CharField(max_length=500)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
    ]
